### ISSUE TITLE
Status Check

### ISSUE THREAD

**Issue by idkjs** [Huxpro/real-world-reason#1]
Hello @Huxpro! Thanks for starting this.

Is this still a thing? Is there some reason we should not be moving forward? 

I noticed work seems to have stopped.

Thank you, sir.

**Comment by Huxpro** [comment]
Thanks for asking. The main reasons are:
1. I don't have spare bandwidth for this.
2. Reason has both native/JS backend. It seems too trivial to add Reason Native to RWO and too hard/unclear to coerce Reason JS into RWO.
3. Better documentation effort from community is going on: <https://reasonml.org/>.

**Comment by idkjs** [comment]
This had a really good start, though. Maybe stick the design setting in a file in case anyone wants to add something here and there. It might encourage a fork!

**Comment by Huxpro** [comment]
@idkjs Thanks.

What did you mean by "stick the design setting in a file"?
There is a [conversion guide](https://real-world-reason.gitbook.io/book/meta/conversion-guide) if that's what you were looking for?

**Comment by idkjs** [comment]
I meant to recreate the gitbook with your same styles/css.

**Comment by Huxpro** [comment]
@idkjs I was just using the default gitbook configuration though.

**Comment by idkjs** [comment]
Thanks, brother. I guess need to read up on gitbook.
